version: '3.8'
services:
  db-ecommerce-services:
    image: mysql:8.0
    container_name: ecommerce-db
    environment:
      MYSQL_DATABASE: ecommerce-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - db-ecommerce-data:/var/lib/mysql


  db-ecommerce-services-1.7:
    image: mysql:8.0
    container_name: ecommerce-db-production-test-1.7
    environment:
      MYSQL_DATABASE: ecommerce-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3312:3306"
    volumes:
      - db-ecommerce-data:/var/lib/mysql

  # db-ecommerce-services-demo:
  #   image: mysql:8.0
  #   container_name: ecommerce-db-backend
  #   environment:  
  #     MYSQL_DATABASE: ecommerce-db-backend
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: password
  #   ports:
  #     - "3311:3306"
  #   volumes:
  #     - db-ecommerce-db-backend:/var/lib/mysql

volumes:
  db-ecommerce-data:
  db-ecommerce-db-backend: